// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package codegen

import (
	"database/sql"
)

type Todo struct {
	ID        int64
	Title     string
	Completed sql.NullBool
	CreatedAt sql.NullTime
}
